name: Code Test

on:
  pull_request:
    branches:
      - master
    paths:
      - 'v2rayN/ServiceLib/**'
      - 'v2rayN/ServiceLib.Tests/**'
      - 'v2rayN/AmazTool/**'
      - 'v2rayN/v2rayN/**'
      - '.github/workflows/release-windows-cmcc.yml'
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Setup .NET
      uses: actions/setup-dotnet@v5.4.0
      with:
        dotnet-version: '10.0.1xx'

    - name: Test Code
      working-directory: ./v2rayN
      run: dotnet test ./ServiceLib.Tests
